version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: "database"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
  cache:
    image: redis:6.2-alpine
    container_name: "cache"
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81