# Generated by Django 4.2.5 on 2023-09-14 08:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('password', models.CharField(db_column='password', max_length=255, null=True)),
                ('phone', models.CharField(db_column='phone', max_length=30, null=True)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('status', models.IntegerField(db_column='status', default=0)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refresh_token', models.TextField(db_column='refresh_token')),
                ('access_token', models.TextField(db_column='access_token')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'db_table': 'user_token',
            },
        ),
    ]
